environment:
  TWINE_USERNAME: geostatframework
  CIBW_SKIP: "cp37-*"
  CIBW_BEFORE_BUILD: pip install numpy==1.13.0 cython==0.26

build_script:
  - pip install cibuildwheel==0.10.1
  - cibuildwheel --output-dir wheelhouse
  - python -m pip install twine
  - python -m twine upload --skip-existing --repository-url https://test.pypi.org/legacy/ wheelhouse/*.whl
  - >
    IF "%APPVEYOR_REPO_TAG%" == "true"
    (
    python -m pip install twine
    &&
    python -m twine upload --skip-existing wheelhouse/*.whl
    )
artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels